name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: temurin
        cache: sbt

    - uses: sbt/setup-sbt@v1

    - run: sbt scalafmtCheckAll
    - run: sbt tests/test
    - run: sbt 'set ThisBuild / version := "0.1.0-SNAPSHOT"; library/publishLocal; +rules/publishLocal; plugin/scripted'
