name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - run: sbt scalafmtCheckAll tests/test 'set ThisBuild / version := "0.1.0-SNAPSHOT"; library/publishLocal; +rules/publishLocal; plugin/scripted'
